<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_Indica</name>
   <tag></tag>
   <elementGuidId>225b6a09-9ca1-4f74-8bcd-d55b67ffe0aa</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='shopify-section-fr-header']/div/div[2]/div/div/div/nav/ul/li/div/div[2]/ul/li/div/div/ul/li/a/span</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Indica</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;shopify-section-fr-header&quot;)/div[@class=&quot;header&quot;]/div[@class=&quot;menu-bar&quot;]/div[@class=&quot;menu-bar__content&quot;]/div[@class=&quot;menu-bar__left-wrapper&quot;]/div[@class=&quot;mega-menu js-mega-menu&quot;]/nav[@class=&quot;menu js-menu&quot;]/ul[@class=&quot;menu__list unstyled&quot;]/li[@class=&quot;menu__tier-one js-menu__tier-one has-tier-two-open&quot;]/div[@class=&quot;menu__tier-two js-menu__tier-two menu__tier-two--with-footer&quot;]/div[@class=&quot;menu__tier-two__content-container clearfix&quot;]/ul[@class=&quot;unstyled no-margin menu__tier-two__menu-primary&quot;]/li[@class=&quot;menu__tier-three menu--type-one js-menu__tier-three&quot;]/div[@class=&quot;accordion-item__nested-container accordionize__content accordionize__content--mega-menu&quot;]/div[1]/ul[@class=&quot;unstyled&quot;]/li[@class=&quot;menu__tier-four&quot;]/a[@class=&quot;menu__tier-four__link&quot;]/span[1]</value>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <value>//div[@id='shopify-section-fr-header']/div/div[2]/div/div/div/nav/ul/li/div/div[2]/ul/li/div/div/ul/li/a/span</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Fleurs séchées'])[1]/following::span[1]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Cannabis'])[2]/following::span[2]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Sativa'])[1]/preceding::span[1]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Hybride'])[1]/preceding::span[2]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <value>//div[2]/ul/li/div/div/ul/li/a/span</value>
   </webElementXpaths>
</WebElementEntity>
